[package]
name = "piecrust-macros"
authors = ["Hein Dauven"]
version = "0.1.0"
edition = "2021"
description = "Macro library for the Dusk Piecrust VM"

[dependencies]
syn = { version = "2.0.44", features = ["full"] }
quote = "1.0.34"
piecrust-uplink = "0.9.0"

[lib]
proc-macro = true